# Generated by Django 3.0.6 on 2020-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='음식명')),
                ('recipe', models.TextField(verbose_name='요리법')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='레시피')),
            ],
        ),
    ]
