# Generated by Django 3.0.6 on 2020-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='음식명'),
        ),
    ]
